server:
  port: 8080

spring:
  application:
    name: cliper-client
  datasource:
    url: jdbc:h2:mem:cliperDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    root: warn
    org.springframework: error