name: Check Branch Name

on:
  create:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "Checking branch name $GITHUB_REF"
          if [[ "${GITHUB_REF#refs/heads/}" =~ ^(hotfix|feature|bugfix|release)/[a-z0-9_-]+$ ]]; then
            echo "Branch name is valid"
          else
            echo "Invalid branch name: ${GITHUB_REF#refs/heads/}"
            exit 1
          fi